name: Generate GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # runs every day at midnight
  workflow_dispatch: # allows manual runs
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_code_review: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: public
          plugin_activity_filter: all
          plugin_traffic: yes
          plugin_repositories: yes
          plugin_languages: yes
          plugin_introduction: yes
          plugin_people: yes
          plugin_achievements_secrets: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts_type: classic
